### PR TITLE
✅New icon

### PR DESCRIPTION
**Pull request by ghost**
I created a new page small icon instead of the old one.

### CODE REVIEW

**Review by moeenio — COMMENTED** [review]
I think we could go without text, just the rounded gradient rectangle, especially as a small favicon. Also did you use 10px border radius ?

**Comment by ghost** [comment]
Ok. It's a 500x500px square, and i used 25% border radius, which makes 125px in this case.

**Comment by moeenio** [comment]
Well, please update with 10px radius (consistency :P)

**Comment by ghost** [comment]
Done ! New logo without text.

**Comment by delnyn** [comment]
Oh wait

**Comment by ghost** [comment]
But 10px radius on 500px is very small (we almost can't see it). Maybe 10% ?

**Comment by moeenio** [comment]
Just make it 100px. (the image, not the radius)

**Comment by ghost** [comment]
Done.

**Review by moeenio — APPROVED** [review]
Looks good!

**Pull request merged**
