### PR TITLE
deprecation notice

### PR DESCRIPTION
**Pull request by moeenio**
since this website is still often getting visits (in majority from the gravity tutorial) I'm adding a notice with a contact email if someone wants to maintain it - it'll actually have visibility

@delnyn

### CODE REVIEW

**Comment by ghost** [comment]
ookay

**Comment by moeenio** [comment]
rien reçu bruh

**Comment by ghost** [comment]
je suis pas surpris

**Comment by moeenio** [comment]
beuh

**Comment by ghost** [comment]
ok

**Comment by moeenio** [comment]
a

**Comment by ghost** [comment]
breffff

**Comment by moeenio** [comment]
retirons cette vieille bannière de cookies et mettons tarteaucitron.js à la place

**Pull request merged**
