### PR TITLE
Use CSS variables instead of SCSS variables

### LINKED ISSUE #15: Use CSS variables instead of SASS variables
Would allow for #12 

While I'm at it, I should rename them to follow [this Figma](https://www.figma.com/file/pKHaVKFcPDLDOIQIaOaK6L/Colors-and-Typography?node-id=3%3A2).

### PR DESCRIPTION
**Pull request by ghost**
closes #15.

### CODE REVIEW

**Comment by moeenio** [comment]
Pls use the dark grayple for the body text

**Comment by ghost** [comment]
Done! ✅

**Comment by moeenio** [comment]
No, I think it's better with grayple. But wider problem, dark grayple and grayple don't have enough contrast between them IMO.

**Comment by ghost** [comment]
I'll switch colors later. But for the contrast, you have to pick colors

**Comment by ghost** [comment]
Able to merge ?

**Comment by moeenio** [comment]
I guess

**Pull request merged**
