### PR TITLE
:sparkles: Add category, tag, difficulty and author support

### PR DESCRIPTION
**Pull request by moeenio**
- [x] Add layout for category pages
- [x] Add layout for tag pages
- [x] Add layout for author pages
- [x] ~~Add layout for difficulty pages?~~
- Show in post lists
  - [x] Categories
  - [x] Tags
  - [x] Difficulty
  - [x] Author
- Show on single posts
  - [x] Categories
  - [x] Tags
  - [x] Difficulty
  - [x] Author

Adding these to posts is a task for csourcesc/content.

@delnyn

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Great work! Just to know, why are the icons HTML files and not SVG files? Also how do I preview Author page and Category page?

**Comment by moeenio** [comment]
> Just to know, why are the icons HTML files and not SVG files?

They aren't SVG files as they are meant to be integrated inline within the HTML; SVG files need some additionnal stuff that shouldn't be in inline SVGs.
> Also how do I preview Author page and Category page?

The category and author pages need to be added to the content repository. Though you can clone the repo and add some dummy pages to test.

**Review by ghost — APPROVED** [review]

**Comment by moeenio** [comment]
Now I think about it, there will likely be a lot of tags on articles. I think we'd be better using a plugin like jekyll-archives for tag pages.

**Comment by ghost** [comment]
Do what you want, I'm not able to help to dev 😅

**Comment by moeenio** [comment]
Settled on using it for both categories and tags.

Do we do difficulty pages, though?

**Comment by ghost** [comment]
I'm not sure this is very useful

**Comment by moeenio** [comment]
Yeah, let's not do difficulty pages.

**Review by ghost — APPROVED** [review]

**Pull request merged**
