### PR TITLE
:lipstick: New footer icons + remove useless ones

### PR DESCRIPTION
**Pull request by moeenio**
Make the footer social icons more modern, and remove unused ones.
Screen Shot 2020-04-28 at 09 40 23

They are based off icons from simpleicons.org and materialdesignicons.com.
## Todo
- [x] Do the mail icon

### CODE REVIEW

**Comment by moeenio** [comment]
cc @delnyn

**Comment by moeenio** [comment]
I added credit for the icons (except the mail one, I'll add it when done)

**Comment by ghost** [comment]
simpleicons.com is cool. Maybe you could use feathericons too ?

**Comment by moeenio** [comment]
No, feathericons have deprecated brand icons. I'll do the mail icon from materialdesignicons.com

**Comment by moeenio** [comment]
I added the mail icon. What do you think @delnyn ?

**Comment by ghost** [comment]
That's cool. What is the feed for ?

**Comment by moeenio** [comment]
The feed icon is for the RSS feed.

**Comment by ghost** [comment]
Oh ok.

**Comment by ghost** [comment]
The YouTube and Mail icons are missing in the Netlify preview

**Comment by ghost** [comment]
> No, feathericons have deprecated brand icons. I'll do the mail icon from materialdesignicons.com

I was talking about flux and mail, not brand icons. But material is cool too :)

**Comment by moeenio** [comment]
> The YouTube and Mail icons are missing in the Netlify preview

Yes, that's normal, they aren't being used on the site.

**Comment by moeenio** [comment]
Yeah, the rss and mail from feather look good, but we're going to stick with material.

**Comment by moeenio** [comment]
Well, I guess we can merge

**Comment by ghost** [comment]
> Yes, that's normal, they aren't being used on the site.

Oh ok. Nice :)

**Pull request merged**
