### PR TITLE
:sparkles: Add danger, info, tip, warn callouts

### PR DESCRIPTION
**Pull request by moeenio**
callout
```liquid
{% include callout.html content="The default callout (no type specified)" %}
{% include callout.html type="tip" content="Friendly tip!" %}
{% include callout.html type="warn" content="Beware! Bad things may happen." %}
{% include callout.html type="info" content="This is for your information." %}
{% include callout.html type="danger" content="Danger! Don't do this!" %}
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good! Also why are the new color variables in HSL and not HEX?

**Comment by moeenio** [comment]
To show that the colors share hue/saturation/brightness

**Comment by ghost** [comment]
okay!

**Comment by moeenio** [comment]
waw ifphoen

**Comment by ghost** [comment]
image

**Comment by moeenio** [comment]
@delnyn \:(

**Comment by ghost** [comment]
?

**Pull request merged**
